[package]
name = "h2"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
futures = "0.1"
tokio-io = "0.1.3"
tokio-timer = "0.1"
bytes = "0.4"
http = { git = "https://github.com/carllerche/http", branch = "lower-case-header-name-parsing" }
byteorder = "1.0"
log = "0.3.8"
fnv = "1.0.5"
slab = "0.4.0"
string = { git = "https://github.com/carllerche/string" }

[dev-dependencies]
mock-io = { git = "https://github.com/carllerche/mock-io", branch = "experiments" }

# Fuzzing
quickcheck = "0.4.1"
rand = "0.3.15"

# HPACK fixtures
hex = "0.2.0"
walkdir = "1.0.0"
serde = "1.0.0"
serde_json = "1.0.0"

# Akamai example
tokio-core = "0.1"
env_logger = "0.4.3"
io-dump = { git = "https://github.com/carllerche/io-dump" }
rustls = "0.11"
tokio-rustls = { git = "https://github.com/briansmith/tokio-rustls", tag = "b/p1" }
webpki-roots = "0.13"
